### ISSUE TITLE
Multiple sorts & duplicate values in sort fields

### ISSUE THREAD

**Issue by ahmedriad1** [brietsparks/knex-relay-cursor-pagination#4]
Hey,

Thank you for this amazing package! I've been trying to migrate from Prisma to Mikro-ORM due to a huge problem. Just wanted to ask, I see it's not implemented yet, but is it possible to sort by multiple columns? Also, I notice there is an issue while sorting by fields tha have repeated values: it just skips some rows.

Regards

**Comment by brietsparks** [comment]
Hey, thanks for your question! Currently, the pagination params expect the sorted values to be unique. I will look into supporting multiple sort criteria.

For now, I would recommend try deriving an additional column based on the sorted column plus a unique-values column such as the pk, so that the derived column has sorted, unique values.

Here is an example of that from the tests. The pagination sorts posts by their comment-count, which can have duplicate values across posts. A derived column is created by concatenating the comment-count with the post id.

https://github.com/brietsparks/knex-relay-cursor-pagination/blob/master/test/knex-relay-cursor-pagination.test.ts#L503
```
const cte = db
        .from('posts')
        .select(
          'posts.*',
          db.raw(
            `concat(count("comments"."id"), ':', "posts".id) as comments_count`
          )
        )
        .leftJoin('comments', 'posts.id', 'comments.post_id')
        .groupBy('posts.id')
        .orderBy('comments_count', 'desc');

      const pagination = createPagination({
        ...baseParams,
        ...testCase.sliceParams,
      });

      const rows = await db
        .with('cte', cte)
        .from('cte')
        .where(
          pagination.where.column,
          pagination.where.comparator,
          pagination.where.value
        )
        .orderBy(pagination.orderBy.column, pagination.orderBy.direction)
        .limit(pagination.limit)
        .select('id', 'title', 'creation_timestamp');
```

**Comment by ahmedriad1** [comment]
@brietsparks  That solves my issue. TYSM!
